### ISSUE TITLE
ssh keys and host list has to be generalized

### ISSUE THREAD

**Issue by gisma** [Nature40/Sensorboxes-Images#9]
It would be very helpful to provide a hostlist and general ssh key on all Pis for an easy and secure cross over connection. Similiar to that what is described here: http://giswerk.org/doku.php?id=wac:modeling:arps:mpi_arps2beo#beowulf-cluster_-_zugeschaut_mitgebaut

**Comment by oxzi** [comment]
I would recommend deploying the same key pair on each client. Furthermore, the public key should be inserted in the `known_hosts` and `authorized_keys` files for both `pi` and `root`. Otherwise one has to manually configure keys for each *planet/moon* tuple to get `rsync` working. I don't thinks this would have a big security impact, based on the fact that all station's SD cards could be taken anyway.
